---
# handlers file for setup-apache
- name: start_apache
  service:
    name: httpd
    state: started
  when: ansible_os_family == "RedHat"

- name: start_apache2
  service:
    name: apache2
    state: started
  when: ansible_os_family == "Debian"

- name: restart_apache
  service:
    name: httpd
    state: restarted
  when: ansible_os_family == "RedHat"

- name: restart_apache2
  service:
    name: apache2
    state: restarted
  when: ansible_os_family == "Debian"

