---
- name: "This playbook install packages"
  hosts: all 
  become: true
  tasks:
  - name: "Install package"
    yum:
      name: httpd
      state: installed
    when: ansible_os_family == "RedHat"

  - name: "Start httpd service"
    service:
      name: httpd
      state: started
    when: ansible_os_family == "RedHat"

  - name: "Install apache2 package"
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "Debian"

  - name: "Start apache2 service"
    service:
      name: apache2
      state: started
    when: ansible_os_family == "Debian"

  - name: copy index.html file
    copy:
      src: /opt/ansible/index.html
      dest: /var/www/html
      mode: 0666
    tags: copy_index_file
