---
- name: "This playbook install packages"
  hosts: all 
  become: true
  tasks:
  - name: "Stopping httpd service"
    service:
      name: httpd
      state: stopped
    when: ansible_os_family == "RedHat"

  - name: "Uninstall package"
    yum:
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"

  - name: "Stopping apache2 service"
    service:
      name: apache2
      state: stopped
    when: ansible_os_family == "Debian"

  - name: "Uninstall apache2 package"
    apt:
      name: apache2
      state: absent
    when: ansible_os_family == "Debian"

